spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/hapi'
    username: "admin"
    password: "admin"
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
hapi:
  fhir:
    custom-bean-packages: com.hemeo.interceptors
    custom-interceptor-classes: com.hemeo.interceptors.AuthenticationInterceptor
