version: "3.7"

services:
  fhir-server:
    image: hemeo-hapi-fhir-server
    ports:
      - "8080:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://host.docker.internal:5432/hapi'
      spring.datasource.username: "admin"
      spring.datasource.password: "admin"
      spring.datasource.driverClassName: org.postgresql.Driver
      IAM_INTROSPECTION_ENDPOINT: "http://host.docker.internal:9090/realms/HEMEO/protocol/openid-connect/token/introspect"
      IAM_CLIENT_AUTH: "aGVtZW86M05PMG9TMUhoRXE1cXoydXVzVkNIR1ZxalpDSDlkaVM="
    depends_on:
      - hapi-fhir-postgres

  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    ports:
        - 5432:5432

volumes:
  hapi-fhir-postgres: